name: release-artifacts

on:
  release:
    types: [published]

# Make sure the GITHUB_TOKEN has permission to upload to our releases
permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Build the artifacts and upload
      - name: build-and-upload
        run: |
          cd ${{github.workspace}}
          make clean build-all
          find bin/verifyctl-* -type f -exec sh -c "gh release upload --clobber ${{github.event.release.tag_name}} {}; echo {} uploaded to ${{github.event.release.tag_name}}" \;
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash