name: validate-build

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, edited, reopened, synchronize ]
    branches:
      - main
  merge_group:
    types: [ checks_requested ]

jobs:
  bin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate code
        run: make generate
      - name: Build verifyctl
        run: make clean build
      - name: Build all variants of verifyctl
        run: make clean build-all
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build verifyctl image
        run: make clean build build-image
